name: CI/CD Pipeline

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['main']

env:
  BACKEND_DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/Sportify_Back
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        id: docker_login
        continue-on-error: false

      - name: Check Docker Login Status
        if: steps.docker_login.outcome == 'failure'
        run: |
          echo "Failed to log in to Docker Hub"
          exit 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./Sportify_Back
          file: ./Sportify_Back/Dockerfile
          push: true
          tags: |
            ${{ env.BACKEND_DOCKER_IMAGE }}:latest
            ${{ env.BACKEND_DOCKER_IMAGE }}:${{ github.sha }}
          build-args: |
            NODE_ENV=production
          no-cache: true
